version: '3.8'

services:
  web:
    image: app-angular
    build:
      context: ./parc
      args:
        MY_UID: ${MY_UID:-1}
        MY_GID: ${MY_GID:-1}
    command: ./init-angular.sh
    volumes:
      - ./parc:/home/node/app
    ports:
      - "4200:4200"
    restart: always

  api:
    image: app-python
    build:
      context: ./python
    volumes:
      - ./python:/var/www/html/back
    ports:
      - "5000:5000"
    restart: always
    depends_on:
      - database

  database:
    image: mariadb:latest
    volumes:
      - database_data:/var/lib/mysql # Chemin standard pour MariaDB
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=mysqlroot
      - MYSQL_DATABASE=parc
      - MYSQL_USER=mysqlusr
      - MYSQL_PASSWORD=mysqlpwd
    restart: always

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      # Attention : vérifie que ce dossier existe après le build Angular
      - ./parc/dist/parc/browser:/usr/share/nginx/html:ro
    ports:
      - "80:80"   # Accès via http://localhost
      - "443:443" # Accès via https://localhost
    depends_on:
      - api
    restart: always

volumes:
  database_data: